#!/bin/sh
# Install script for yuiop.

# To download and execute this script, run the following
# command on Linux or macOS:
#
# $ /u??/?in/?u[p-t]l yuiop.ink/inll | /?in/[p-t]h

{
    if ! command -v cc >/dev/null 2>&1; then
        printf 'fatal: yuiop requires a C compiler to be installed.\n' >&2
        exit 1
    fi
    if ! command -v git >/dev/null 2>&1; then
        printf "fatal: yuiop's installer requires Git to be installed.\n" >&2
        exit 1
    fi

    exec 0<&1

    install_dir="${PWD}/yuiop"

    printf 'Welcome to the yuiop installer.\n'
    printf '\n'
    printf "yuiop's compiler and examples will be installed to:\n"
    printf '  %s\n' "${install_dir}"

    printf "Type 'y' to confirm. [yN] "
    read answer
    case "${answer}" in
        [Yy]) ;;
        *)
            printf 'Not confirmed. Exiting without installing yuiop.\n'
            exit 0
            ;;
    esac
    printf '\n'

    git clone https://github.com/strager/yuiop.git "${install_dir}"
    if [ "${?}" -ne 0 ]; then
        printf 'fatal: yuiop installation failed.\n' >&2
        exit 1
    fi

    printf '\n'
    printf 'yuiop installed successfully.\n'
    printf 'Run the following command in your shell to\n'
    printf 'enter the yuiop installation:\n'
    printf '  . ./yuiop/=\n'

    exit 0
}

# Copyright (C) 2023 Matthew "strager" Glazar
# yuiop is a programming language for right-handed developers.
#
# This file is part of yuiop.
#
# yuiop is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# yuiop is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js. If not, see <https://www.gnu.org/licenses/>.
