#!/bin/sh

set -e
set -u

cat >/tmp/yuiop.h <<EOF
typedef int i;
#define mn main

int p(const char*, ...) asm("_printf");
EOF

tr -c -d '67890-=yuiop[]hjkl;nm,./^&*()_+YUIOP{}|HJKL:"NM<>? '\'\\ <"${1}" \
    | cc -include /tmp/yuiop.h -o /tmp/yuiop.exe -x c /dev/stdin
shift
exec /tmp/yuiop.exe "${@}"
